install:
  - choco install gitversion.portable -pre -y
  
before_build:  
  - .paket\paket.bootstrapper.exe prerelease
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

build:
  project: Nancy.ProblemDetails.sln

configuration: Release

after_build:
  - .paket\paket.exe pack output nugets include-referenced-projects version %GitVersion_NuGetVersion%
  
after_test:
  - .\packages\OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"Tests\Nancy.ProblemDetails.Tests\bin\Release\Nancy.ProblemDetails.Tests.dll -noshadow -appveyor" -returntargetcode -filter:"+[Nancy.ProblemDetails*]* -[Nancy.ProblemDetails.Tests*]* -[Test*]*" -hideskipped:All -output:.\Nancy.ProblemDetails_coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "Nancy.ProblemDetails_coverage.xml"

artifacts:
  - path: 'nugets\*.nupkg'
  - path: Nancy.ProblemDetails_coverage.xml

cache:
  - packages -> paket.lock
  
deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true